### ISSUE TITLE
pip install . throws error

### ISSUE THREAD

**Issue by sonofmun** [OpenPhilology/Iris#6]
When I run pip install . using a clean virtualenv I get the following output:

Processing /home/mmunson/Iris
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-3IsCBq-build/setup.py", line 13, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/home/mmunson/envs/Iris/local/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-3IsCBq-build/setup.py", line 13, in <module>
    
        reqs = [str(ir.req) for ir in install_reqs]
    
      File "/home/mmunson/envs/Iris/local/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    
        "parse_requirements() missing 1 required keyword argument: "
    
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-3IsCBq-build

**Comment by sonofmun** [comment]
I can get it to install the required packages using:

    pip install -r requirements.txt

**Comment by sonofmun** [comment]
BTW, I was running this on the Homer server.

**Comment by sonofmun** [comment]
But I get this error when I try to run `python setup.py download`

    Traceback (most recent call last):
        File "setup.py", line 13, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
    File "/home/mmunson/envs/Iris/local/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'

The error is the same as the problem with `pip install .`

**Comment by sonofmun** [comment]
The problem is with pip 6.0.6., the newest release of pip.  A line to install pip==1.5.4 is needed or the installation needs to be made compatible with the newest version of pip.

**Comment by mittagessen** [comment]
It's fixed in my branch. Pip changed the syntax of the parse_requirements function to require a session identifier.
